### PR TITLE
Log to log_root+..._log except if ..._log is absolute

### LINKED ISSUE #542: Specifying a backend on /tmp prevents lager from booting up
As mentioned here: https://github.com/erlang-lager/lager/commit/ccb3c109722c6deafc08bc5dcc89ce570ad9e5a9#commitcomment-47584989 …

Using the following configuration…

```erlang
[{lager, [{crash_log, "/tmp/crash.log"}]}].
```

…this happens…

```erlang
1> application:ensure_all_started(lager).
=SUPERVISOR REPORT==== 26-Feb-2021::08:54:40.333756 ===
    supervisor: {local,lager_sup}
    errorContext: start_error
    reason: {{case_clause,"/tmp"},
             [{lager_util,expand_path,1,
                          [{file,"/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_util.erl"},
                           {line,467}]},
              {lager_crash_log,init,1,
                               [{file,"/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_crash_log.erl"},
                                {line,76}]},
              {gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},
              {gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,undefined},
               {id,lager_crash_log},
               {mfargs,
                   {lager_crash_log,start_link,
                       ["/tmp/crash.log",65536,10485760,
                        [{hour,0}],
                        5,lager_rotator_default]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
=CRASH REPORT==== 26-Feb-2021::08:54:40.336261 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.95.0>
    registered_name: []
    exception exit: {bad_return,
                     {{lager_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,lager_crash_log,
                            {{case_clause,"/tmp"},
                             [{lager_util,expand_path,1,
                               [{file,
                                 "/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_util.erl"},
                                {line,467}]},
                              {lager_crash_log,init,1,
                               [{file,
                                 "/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_crash_log.erl"},
                                {line,76}]},
                              {gen_server,init_it,2,
                               [{file,"gen_server.erl"},{line,374}]},
                              {gen_server,init_it,6,
                               [{file,"gen_server.erl"},{line,342}]},
                              {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,249}]}]}}}}},
                        [{lager_app,start,2,
                          [{file,
                            "/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_app.erl"},
                           {line,227}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.94.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.96.0>,normal}]
    links: [<0.94.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 184
  neighbours:

=INFO REPORT==== 26-Feb-2021::08:54:40.338217 ===
    application: lager
    exited: {bad_return,
             {{lager_app,start,[normal,[]]},
              {'EXIT',
               {{badmatch,
                 {error,
                  {shutdown,
                   {failed_to_start_child,lager_crash_log,
                    {{case_clause,"/tmp"},
                     [{lager_util,expand_path,1,
                       [{file,
                         "/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_util.erl"},
                        {line,467}]},
                      {lager_crash_log,init,1,
                       [{file,
                         "/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_crash_log.erl"},
                        {line,76}]},
                      {gen_server,init_it,2,
                       [{file,"gen_server.erl"},{line,374}]},
                      {gen_server,init_it,6,
                       [{file,"gen_server.erl"},{line,342}]},
                      {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,249}]}]}}}}},
                [{lager_app,start,2,
                  [{file,
                    "/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_app.erl"},
                   {line,227}]},
                 {application_master,start_it_old,4,
                  [{file,"application_master.erl"},{line,277}]}]}}}}
    type: temporary
=INFO REPORT==== 26-Feb-2021::08:54:40.339023 ===
    application: goldrush
    exited: stopped
    type: temporary
=INFO REPORT==== 26-Feb-2021::08:54:40.339164 ===
    application: compiler
    exited: stopped
    type: temporary
{error,{lager,{bad_return,{{lager_app,start,[normal,[]]},
                           {'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,lager_crash_log,
                                                                                      {{case_clause,"/tmp"},
                                                                                       [{lager_util,expand_path,1,[{file,...},{...}]},
                                                                                        {lager_crash_log,init,1,[{...}|...]},
                                                                                        {gen_server,init_it,2,[...]},
                                                                                        {gen_server,init_it,6,...},
                                                                                        {proc_lib,init_p_do_apply,...}]}}}}},
                                    [{lager_app,start,2,
                                                [{file,"/Users/fernandobenavides/Projects/NextRoll/svetch/_build/default/lib/lager/src/lager_app.erl"},
                                                 {line,227}]},
                                     {application_master,start_it_old,4,
                                                         [{file,"application_master.erl"},{line,277}]}]}}}}}}
=INFO REPORT==== 26-Feb-2021::08:54:40.339270 ===
    application: syntax_tools
    exited: stopped
    type: temporary
```

This happens, at least in OTP22 and OTP23.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
This is a proposed fix that hopefully closes #542.~~, to get early feedback.~~

Apart from the obvious variable re-naming (it's not a rel. path anymore), I went with the approach described [here](https://github.com/erlang-lager/lager/issues/542#issuecomment-786599680).

I also prevent the `application:get_env` from being called when it's not required. Mind you, this is untested still.

---

**Edit**: what's done?
- [x] fix the issue described in https://github.com/erlang-lager/lager/issues/542#issue-817131138
- [x] implement the comment described in https://github.com/erlang-lager/lager/issues/542#issuecomment-786599680
- [x] fix previously existing test issues (from `master`)
- [x] remove `appveyor.yml`
- [x] add Windows GitHub Actions for OTP 23.2

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon
@michaelklishin

**Comment by paulo-ferraz-oliveira** [comment]
Basic local tests, for this, worked for me.

Let me know, so we can try and push a fix out.

**Comment by paulo-ferraz-oliveira** [comment]
Oh, good, tests are failing, which means that these changes are somewhat already covered, but weren't completely, in the past. I'll look at the results.

**Comment by paulo-ferraz-oliveira** [comment]
Regarding the issue expressed in https://github.com/erlang-lager/lager/issues/534, I'm not sure we can achieve such an effect, unless we keep state somewhere.

i.e. if you change path within your application (as expressed by `cd("log")` in that issue), is it not expected to change the log path? You can always use an absolute path to circumvent this. Thoughts?

**Review by elbrujohalcon — APPROVED** [review]

File: src/lager_util.erl [hunk 1]
```diff
@@ -459,22 +459,15 @@ i3l(I) when I < 100 -> [$0 | i2l(I)];
...
-                               RelPath
-                       end;
-                   undefined -> % No log_root given, keep relative path
-                       RelPath
-               end,
-    %% see #534 make sure c:cd can't change file path, trans filename to abs name
-    filename:absname(RelPath2).
+expand_path(LogPath) ->
+    IsLogPathAbsolute = filename:absname(LogPath) =:= LogPath,
+    case IsLogPathAbsolute of
```
Comment (Vagabond) [inline src/lager_util.erl:464]: Suggest removing this intermediate var and just doing the check in the case head?

Comment (paulo-ferraz-oliveira) [reply src/lager_util.erl:464]: Sure.

Comment (paulo-ferraz-oliveira) [reply src/lager_util.erl]: Squashed over the previous commit. I still have to look at why the tests are failing, though.

**Comment by Vagabond** [comment]
@paulo-ferraz-oliveira since you added GHA, can you look at what the failures are here?

Also I think this PR can be taken out of draft state.

**Comment by paulo-ferraz-oliveira** [comment]
I'm looking at the errors 😄.

```erlang
filename:join("", LogPath). 
"/foo/bar"
```

isn't my initial expectation, so I'll have to add a newer case clause.

I'll remove from draft: I just wanted to signal it's still being developed and not ready for merge, but I guess GHA can take care of that.

**Comment by paulo-ferraz-oliveira** [comment]
@Vagabond: I had to change the `case` slightly, as per what I mentioned in the previous comment.

**Comment by paulo-ferraz-oliveira** [comment]
@Vagabond, I remove `appveyor` as previously suggested, since this gets in the way of understand if tests broke. Is there any way we could easily update this to work with Windows? I know nothing about `appveyor`.

**Review by Vagabond — APPROVED** [review]

**Comment by Vagabond** [comment]
This looks good, nice work. I'll have @mrallen1 take a look and if he's ok with it as well maybe we can round up any other PRs and a cut a bugfix release.

**Review by mrallen1 — APPROVED** [review]
👍 lgtm

**Comment by mrallen1** [comment]
Thanks so much!

**Comment by michaelklishin** [comment]
@paulo-ferraz-oliveira a quick test suggests that on your branch, RabbitMQ nodes successfully start with some changes we are willing to accept. So, this looks promising.

**Comment by michaelklishin** [comment]
This fixes a serious bug IMO, any progress on getting this in?

**Comment by michaelklishin** [comment]
Thank you!
