### PR TITLE
Ensure relative log file not change when current path changed

### LINKED ISSUE #534: when change pwd, RelPath will also change, and create new log file in new dir
with env
```erlang
{lager, [
        {log_root, "./log"},
        {crash_log, "crash.log"}
    ]
    },
```
after call `cd("log").` 
crash log will make new file in ./log/log/crash.log not continue write in ./log/crash.log
seems because when ensure log file，use rel file name，and rel file changed because of pwd changed
https://github.com/erlang-lager/lager/blob/91575d4479c897451edf138c10fa86c3125ec52e/src/lager_util.erl#L601-L604
then will create new log file
https://github.com/erlang-lager/lager/blob/91575d4479c897451edf138c10fa86c3125ec52e/src/lager_rotator_default.erl#L44-L47

same behavior in lager_file_backend, not sure this is mean to.
if not seems just change laget_util:expand_path from rel path to abs will resolve this，if this is fine，i could make a pr for this.

if mean to, maybe add a env key like `use_abs_path` or `abs_log_root` let config control is a way too

### PR DESCRIPTION
**Pull request by yidayoung**
Fix #534 
- Change lager_util:expand_path function will return abspath not relative
- Fix testcase of expand_path
- Delete function filename:absname call in lager_util:find_file，because of lager_util:expand_path will return abspath

### CODE REVIEW

File: src/lager_util.erl [hunk 1]
```diff
@@ -460,19 +460,21 @@ i3l(I)              -> integer_to_list(I).
...
-            end;
-        undefined -> % No log_root given, keep relative path
-            RelPath
-    end.
+    RelPath2 = case application:get_env(lager, log_root) of
+                   {ok, LogRoot} when is_list(LogRoot) -> % Join relative path
+                       %% check if the given RelPath contains LogRoot, if so, do not add
+                       %% it again; see gh #304
+                       case string:str(filename:dirname(RelPath), LogRoot) of
+                           X when X > 0 ->
```
Comment (paulo-ferraz-oliveira) [inline src/lager_util.erl:468]: This seems to work badly for e.g. `console.log`  and `log`, since root is part of the former, in terms of matching.

Comment (yidayoung) [reply src/lager_util.erl:468]: Yes, `string:str` is not so precise, this change commited in #317 to fix #304.
this pr change nothing with it.  

------

maybe should make a new pr or issue to specially discuss this,
 i saw https://github.com/erlang-lager/lager/issues/304#issuecomment-164807302 said should trans path to abspath. not not do this finally, maybe there has some other to avoid

Comment (paulo-ferraz-oliveira) [reply src/lager_util.erl:468]: Yeah, sorry, my bad. I didn't mean to imply your pull request changed it in any way. It was simply the most recent one I found "dealing" with this.

I think ```https://github.com/erlang-lager/lager/commit/b9ce226bff4b47f93a4aeac6bbd34bcf78412a8d``` might to the trick: it's part of another pull request I'm currently preparing. Maybe @mrallen1 can help out, here.

Comment (paulo-ferraz-oliveira) [reply src/lager_util.erl:468]: The origin might disappear so I'm pasting the code here `filename:dirname(RelPath) =:= filename:basename(LogRoot)`: it basically compares the first folder.
